@startwbs
skinparam defaultFontName "Georgia"
skinparam defaultFontSize 18
skinparam shadowing false
skinparam WBSFontColor #111111
skinparam WBSBorderColor #333333
skinparam WBSBackgroundColor #ffffff

* Personality Traits

** Extraversion
*** assertive
*** talkative
*** sociable

** Conscientiousness
*** organised
*** efficient
*** reliable

** Agreeableness
*** warm
*** modest
*** kind

@endwbs